# Generated by Django 3.2.9 on 2021-11-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareRes', '0002_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
